apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-model-api
  labels:
    app: diabetes-model-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetes-model-api
  template:
    metadata:
      labels:
        app: diabetes-model-api
    spec:
      containers:
      - name: diabetes-model-api
        image: Your docker username/diabetes-prediction-api:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-model-api-service
spec:
  selector:
    app: diabetes-model-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer